"""Generate a Markdown report from the ResultStore."""

from __future__ import annotations
from datetime import datetime
from storage.result_store import ResultStore


def generate_report(store: ResultStore) -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# AI Code Review Report",
        "",
        f"**Project:** {store.repo_name}  ",
        f"**Generated:** {now}  ",
        f"**Files Reviewed:** {store.total_files}  ",
        f"**Analysis Time:** {store.elapsed_seconds}s  ",
        "",
        "---",
        "",
        "## Summary",
        "",
        "| Metric | Count |",
        "|--------|-------|",
        f"| Total Files    | {store.total_files}    |",
        f"| Total Issues   | {store.total_issues}   |",
        f"| 🔴 Critical    | {store.critical_count} |",
        f"| 🟠 High        | {store.high_count}     |",
        f"| 🟡 Medium      | {store.medium_count}   |",
        f"| 🟢 Low         | {store.low_count}      |",
        f"| ✅ Clean Files | {store.clean_files}    |",
        "",
        "---",
        "",
        "## Issues by File",
        "",
    ]

    sev_icon = {"Critical":"🔴","High":"🟠","Medium":"🟡","Low":"🟢"}

    for r in store.sorted_by_severity():
        lines += [f"### 📄 `{r.path}`", ""]
        if r.summary:
            lines += [f"**Summary:** {r.summary}", ""]
        if not r.issues:
            lines += ["✅ No issues found.", ""]
            continue
        lines.append(f"**{r.total_issues} issue(s):**\n")
        for issue in sorted(r.issues, key=lambda i: {"Critical":0,"High":1,"Medium":2,"Low":3}.get(i.severity,3)):
            icon = sev_icon.get(issue.severity, "🟢")
            lines += [
                f"#### {icon} [{issue.severity}] {issue.title}", "",
                f"**Description:** {issue.description}", "",
                f"**Fix:** {issue.fix}", "",
            ]

    lines += [
        "---", "",
        "## Recommendations", "",
        "1. **Critical** — fix immediately, serious security or crash risk.",
        "2. **High** — schedule for current sprint.",
        "3. **Medium** — add to backlog.",
        "4. **Low** — address during routine code review.", "",
        "---", "",
        "*Generated by AI Code Review Assistant · Gemini 2.0 Flash · Google AI*",
    ]
    return "\n".join(lines)
